改一下
suyiiyii/SIMS pull request #16
Opened 2024-08-16 08:18 UTC by tortoise014

2024-08-16 18:52 UTC, suyiiyii commented on src/main/java/top/suyiiyii/sims/controller/RecordController.java
> +            recordDto.setName(user.getUsername());
用个modelmapper做字段的映射吧，不要手写这么多，又丑又难以维护

2024-08-19 15:31 UTC, tortoise014 commented on src/main/java/top/suyiiyii/sims/controller/RecordController.java
> +            recordDto.setName(user.getUsername());
我看看

2024-08-19 17:51 UTC, suyiiyii requested changes

2024-08-19 17:51 UTC, suyiiyii commented on src/main/java/top/suyiiyii/sims/controller/RecordController.java
> +            recordDto.setReason(record.getReason());
modelmapper!!!

2024-08-19 17:51 UTC, suyiiyii commented on src/main/java/top/suyiiyii/sims/dto/RecordDto.java
> +    private List<String> roles;
角色信息不用出现在Record中吧

2024-08-20 03:32 UTC, suyiiyii commented
要不先尝试一步步来，把 #11 这个做好？

2024-08-20 17:26 UTC, suyiiyii requested changes

2024-08-20 17:26 UTC, suyiiyii commented on src/main/java/top/suyiiyii/sims/controller/RecordController.java
> +        List<RecordDto> recordDtos=new ArrayList<>();
不要在controller里面解析jwt，直接使用jwt拦截器解析出来的结果就行了

2024-08-21 13:25 UTC, suyiiyii approved these changes

2024-08-21 13:27 UTC, tortoise014 commented on src/main/java/top/suyiiyii/sims/controller/RecordController.java
> +        List<RecordDto> recordDtos=new ArrayList<>();
ok

2024-08-21 14:25 UTC, merged