模糊查询
suyiiyii/SIMS pull request #17
Opened 2024-08-23 15:46 UTC by tortoise014

2024-08-24 17:51 UTC, suyiiyii requested changes

2024-08-24 17:51 UTC, suyiiyii commented on src/main/java/top/suyiiyii/sims/controller/RecordController.java
> +            String username,Integer studentId, String userGroup, String grade,String roleName) {
定义一个对象吧，让前端用请求体传过来，这样子散装的不太好

2024-08-24 17:53 UTC, suyiiyii commented
#15

2024-09-01 05:27 UTC, tortoise014 commented on src/main/java/top/suyiiyii/sims/controller/RecordController.java
> +            String username,Integer studentId, String userGroup, String grade,String roleName) {
ok

2024-09-02 09:15 UTC, suyiiyii requested changes

2024-09-02 09:15 UTC, suyiiyii commented on src/main/java/top/suyiiyii/sims/service/RecordService.java
> +        Record record = modelMapper.map(recordDto, Record.class);
注意id的处理，这里不能接受前端传过来的id

2024-09-02 09:15 UTC, suyiiyii commented on src/main/java/top/suyiiyii/sims/service/RecordService.java
> +        Integer categoryId = categoryMapper.getIdBySubCategoryName(recordDto.getSubCategoryName());
这里好像遇到存在的子类型会出问题

2024-09-03 03:40 UTC, tortoise014 commented on src/main/java/top/suyiiyii/sims/service/RecordService.java
> +        Record record = modelMapper.map(recordDto, Record.class);
直接把他传过来的设置成null可以把

2024-09-03 03:40 UTC, tortoise014 commented on src/main/java/top/suyiiyii/sims/service/RecordService.java
> +        Integer categoryId = categoryMapper.getIdBySubCategoryName(recordDto.getSubCategoryName());
改好了

2024-09-07 09:50 UTC, suyiiyii requested changes
调整了获取userId的方式，注意一下

2024-09-07 09:50 UTC, suyiiyii commented on src/main/java/top/suyiiyii/sims/service/RecordService.java
> +        Integer categoryId = categoryMapper.getIdBySubCategoryName(recordDto.getSubCategoryName());
这里好像还是有问题，加一次记录就多一个子类型

2024-09-07 09:50 UTC, suyiiyii commented on src/main/java/top/suyiiyii/sims/service/RecordService.java
> +        Integer categoryId = categoryMapper.getIdBySubCategoryName(recordDto.getSubCategoryName());
![图片](https://github.com/user-attachments/assets/73221636-ac01-4a05-9e44-fa29ec89e7b4)

2024-09-07 09:50 UTC, suyiiyii commented on src/main/java/top/suyiiyii/sims/service/RecordService.java
> +        Integer categoryId = categoryMapper.getIdBySubCategoryName(recordDto.getSubCategoryName());
好像是虽然有报错，但还是添加成功的

2024-09-08 09:35 UTC, tortoise014 commented on src/main/java/top/suyiiyii/sims/service/RecordService.java
> +        Integer categoryId = categoryMapper.getIdBySubCategoryName(recordDto.getSubCategoryName());
我这边不会

2024-09-08 10:52 UTC, suyiiyii approved these changes
合合合，再不合没时间了 XD

2024-09-08 10:52 UTC, merged