表
suyiiyii/SIMS pull request #6
Opened 2024-08-09 14:36 UTC by tortoise014

2024-08-09 15:05 UTC, suyiiyii commented
整体大差不差了
不过有两个需求好像还没设计？

* 普通成员可以向管理员申请撤销某一个奖惩记录
* 管理员可查看所有成员的申请撤销记录，同样需分页展

还有

* 管理员可以撤销某一成员的奖励或惩罚记录，需填写撤销原因

可能还要在搞几张表

2024-08-09 15:05 UTC, suyiiyii requested changes

2024-08-09 15:05 UTC, suyiiyii commented on src/main/java/top/suyiiyii/sims/entity/RewardPunishmentCategory.java
> +
"奖惩分类"也是要分为奖励和惩罚的，也就是说，有一个二级分类

2024-08-09 15:05 UTC, suyiiyii commented on src/main/java/top/suyiiyii/sims/entity/RewardPunishmentRecord.java
> +    private String type;
考虑配合RewardPunishmentCategory表做一个二级分类

2024-08-09 15:52 UTC, tortoise014 commented on src/main/java/top/suyiiyii/sims/entity/RewardPunishmentRecord.java
> +    private String type;
ok

2024-08-10 10:39 UTC, suyiiyii approved these changes

2024-08-10 10:41 UTC, merged