登陆,注册,加上异常集中处理,mybatis和mybatisplus不兼容好像是
suyiiyii/SIMS pull request #9
Opened 2024-08-10 18:11 UTC by tortoise014

2024-08-11 11:08 UTC, suyiiyii commented
仔细看一下[1a602df](https://github.com/suyiiyii/SIMS/pull/9/commits/1a602dfd1d8fc07faa03814c5cec922ae58a5a3d)这个提交，注意一下sql的语法

2024-08-12 06:58 UTC, suyiiyii requested changes

2024-08-12 06:58 UTC, suyiiyii commented on src/main/java/top/suyiiyii/sims/common/JwtInterceptor.java
> +        JWTVerifier jwtVerifier = JWT.require(Algorithm.HMAC256(user.getPassword())).build();//加密,认证
jwt的验证部分抽出来，做一个jwt utils

2024-08-12 06:58 UTC, suyiiyii commented on src/main/java/top/suyiiyii/sims/utils/TokenUtils.java
> +        return JWT.create().withAudience(userId)
这里也是，生成jwt的逻辑抽出来，加到jwt utils里面

2024-08-15 06:00 UTC, suyiiyii requested changes

2024-08-15 06:00 UTC, suyiiyii commented on src/main/java/top/suyiiyii/sims/controller/UserController.java
> +    public Result login(@RequestBody User user){
一个登陆接口，不需要怎么多信息，应该再建一个DTO，专门用来承载登陆请求。其他接口同理

2024-08-15 06:00 UTC, suyiiyii commented on src/main/java/top/suyiiyii/sims/controller/UserController.java
> +    }
不是，哥们
这里就传过来一个密码，怎么判断原密码和更新新密码的

2024-08-15 09:06 UTC, suyiiyii requested changes

2024-08-15 09:06 UTC, suyiiyii commented on src/main/java/top/suyiiyii/sims/VO/UserVO.java
> +package top.suyiiyii.sims.VO;
不用搞VO吧，我们小项目，整个entity和DTO就差不多了

2024-08-15 09:06 UTC, suyiiyii commented on src/main/java/top/suyiiyii/sims/entity/User.java
> +    private Set<Permissions> permissions;
这里之前加上的，不用了记得删掉

2024-08-15 09:06 UTC, suyiiyii commented on src/main/java/top/suyiiyii/sims/service/UserService.java
> +        List<UserVO> userVOS = new ArrayList<>();
这里的VO都换成DTO

2024-08-15 09:35 UTC, tortoise014 commented on src/main/java/top/suyiiyii/sims/controller/UserController.java
> +    }
okok
我看看

2024-08-15 09:35 UTC, tortoise014 commented on src/main/java/top/suyiiyii/sims/VO/UserVO.java
> +package top.suyiiyii.sims.VO;
我可能没有太明白哈哈哈我去学学

2024-08-15 09:36 UTC, tortoise014 commented on src/main/java/top/suyiiyii/sims/entity/User.java
> +    private Set<Permissions> permissions;
这个是用了DTO之后就可以不用这个咯

2024-08-15 09:36 UTC, tortoise014 commented on src/main/java/top/suyiiyii/sims/service/UserService.java
> +        List<UserVO> userVOS = new ArrayList<>();
okok晚上搞

2024-08-15 17:38 UTC, suyiiyii approved these changes

2024-08-15 17:40 UTC, suyiiyii approved these changes

2024-08-15 17:44 UTC, merged